type User {
    id: ID @dataType(type: "Int" autoIncrement: true)
    name: String!
    lastName: String
    login: String!
    salt: String
    hash: String
    email: String
    phones: [String] @map(from: "id" with: {type: "UserPhones" from: "userId" to: "phone"})
    disable: Boolean
    groups: [Group] @map(from: "id" with: {type: "UserGroup" from: "userId" to: "groupId"} to: "id")
    roles: [Role] @map(from: "id" with: {type: "UserRole" from: "userId" to: "roleId"} to: "id")
    realm: Realm @map(from: "realmId" to: "id" anchor: true)
}

type Role {
    id: ID @dataType(type: "Int" autoIncrement: true)
    name: String!
    description: String
    users: [User] @map(from: "id" with: {type: "UserRole" from: "roleId" to: "userId"} to: "id")
    composites: [Role] @map(from: "id" with: {type: "RoleComposite" from: "roleId" to: "compositeId"} to: "id")
    permissions: [Permission] @map(from: "id" with: {type: "RolePermission" from: "roleId" to: "permissionName"} to: "name")
    menus: [Menu] @map(from: "id" with: {type: "RoleMenu" from: "roleId" to: "menuHref"} to: "href")
    realm: Realm @map(from: "realmId" to: "id" anchor: true)
}

type Group {
    id: ID @dataType(type: "Int" autoIncrement: true)
    name: String!
    parent: Group @map(from: "parentId" to: "id" anchor: true)
    subGroups: [Group] @map(from: "id" to: "parentId")
    users: [User] @map(from: "id" with: {type: "UserGroup" from: "groupId" to: "userId"} to: "id")
    roles: [Role] @map(from: "id" with: {type: "GroupRole" from: "groupId" to: "roleId"} to: "id")
    realm: Realm @map(from: "realmId" to: "id" anchor: true)
}

type Realm {
    id: ID @dataType(type: "Int" autoIncrement: true)
    name: String!
}

type Permission {
    name: ID!
    fieldName: String!
    typeName: String!
    description: String
    type: PermissionType
    level: PermissionLevel
    role: [Role] @map(from: "name" with: {type: "RolePermission" from: "permissionName" to: "roleId"} to: "id")
    realm: Realm @map(from: "realmId" to: "id" anchor: true)
}

type Menu {
    href: ID!
    description: String
    type: MenuType!
    path: String
    icon: String
    parent: Menu @map(from: "parentHref" to: "href" anchor: true)
    role: [Role] @map(from: "href" with: {type: "RoleMenu" from: "menuHref" to: "roleId"} to: "id")
    realm: Realm @map(from: "realmId" to: "id" anchor: true)
}

enum PermissionType {
    READ
    WRITE
}

enum PermissionLevel {
    USER
    GROUP
    SUB_GROUP
    REALM
    ALL
}

enum MenuType {
    MENU
    PAGE
}