"用户"
type User implements NamedStruct {
    "ID"
    id: ID @jsonSchema(maxLength: 50)
    "姓名"
    name: String! @options(unique: true) @jsonSchema(minLength: 2 maxLength: 20)
    "描述"
    description: String @jsonSchema(maxLength: 100)
    "姓氏"
    lastName: String @jsonSchema(maxLength: 20)
    "账号"
    login: String! @options(unique: true) @jsonSchema(minLength: 10 maxLength: 20)
    "盐"
    salt: String
    "哈希"
    hash: String
    "邮箱"
    email: String @jsonSchema(maxLength: 50)
    "手机号"
    phones: [String] @jsonSchema(maxLength: 11)
    "禁用"
    disable: Boolean
    "组"
    groups: [Group]
    "角色"
    roles: [Role]
    "租户"
    realm: Realm @map(from: "realmId" to: "id" anchor: true)
}

"角色"
type Role implements NamedStruct {
    "ID"
    id: ID @jsonSchema(maxLength: 50)
    "名称"
    name: String! @options(unique: true) @jsonSchema(minLength: 2 maxLength: 20)
    "描述"
    description: String @jsonSchema(maxLength: 100)
    "用户"
    users: [User]
    "组"
    groups: [Group]
    "组合"
    composites: [Role] @map(from: "id" with: {type: "RoleCompositeRelation" from: "roleRef" to: "compositeRef"} to: "id")
    "权限"
    permissions: [Permission]
    "租户"
    realm: Realm @map(from: "realmId" to: "id" anchor: true)
}

"组"
type Group implements NamedStruct & TreeStruct {
    "ID"
    id: ID @jsonSchema(maxLength: 50)
    "名称"
    name: String! @options(unique: true) @jsonSchema(minLength: 2 maxLength: 20)
    "描述"
    description: String @jsonSchema(maxLength: 100)
    "路径"
    path: String
    "层级"
    deep: Int @jsonSchema(maxLength: 2)
    "上级ID"
    parentId: String
    "上级"
    parent: Group @map(from: "parentId" to: "id" anchor: true)
    "下级"
    subGroups: [Group] @map(from: "id" to: "parentId")
    "用户"
    users: [User]
    "角色"
    roles: [Role]
    "租户"
    realm: Realm @map(from: "realmId" to: "id" anchor: true)
}

"租户"
type Realm implements NamedStruct {
    "ID"
    id: ID @jsonSchema(maxLength: 50)
    "名称"
    name: String! @options(unique: true) @jsonSchema(minLength: 2 maxLength: 20)
    "描述"
    description: String
}

"权限"
type Permission {
    "名称"
    name: ID! @options(type: "String") @jsonSchema(maxLength: 50)
    "描述"
    description: String @jsonSchema(maxLength: 100)
    "字段"
    field: String! @jsonSchema(maxLength: 50)
    "实体"
    type: String! @jsonSchema(maxLength: 50)
    "权限类型"
    permissionType: PermissionType!
    "角色"
    roles: [Role]
    "租户"
    realm: Realm @map(from: "realmId" to: "id" anchor: true)
}

"权限类型"
enum PermissionType {
    "读取"
    READ
    "写入"
    WRITE
}
